USE hris_payroll_app_v2;

-- =========================================================
-- Seed beberapa data karyawan dari sheet
-- Catatan:
-- 1. Password awal semua karyawan: ayres123
-- 2. Email dibuat sementara agar bisa login dan nanti bisa diedit dari web
-- 3. Jika NIP di sheet kosong, dipakai placeholder TMP-xxxx
-- =========================================================

INSERT INTO users (nama, email, password, role, status_aktif) VALUES
  ('Arya Rahadyan', 'arya.rahadyan@ayres.local', SHA2('ayres123', 256), 'karyawan', 1),
  ('Vitus', 'vitus@ayres.local', SHA2('ayres123', 256), 'karyawan', 1),
  ('CB Panjerino Setiaji', 'cb.panjerino@ayres.local', SHA2('ayres123', 256), 'karyawan', 1),
  ('Elnida Rahma Dian, S.Psi., Psikolog', 'elnida.rahma@ayres.local', SHA2('ayres123', 256), 'karyawan', 1),
  ('Humbeina Febriani Imlana Putri', 'humbeina.febriani@ayres.local', SHA2('ayres123', 256), 'karyawan', 1),
  ('Veni Radstya Sari, S.E.', 'veni.radstya@ayres.local', SHA2('ayres123', 256), 'karyawan', 1),
  ('Mizaki Hasan', 'mizaki.hasan@ayres.local', SHA2('ayres123', 256), 'karyawan', 1),
  ('Burhansyah Khalifatur Husna', 'burhansyah.husna@ayres.local', SHA2('ayres123', 256), 'karyawan', 1),
  ('Fiya Agista Rahmadiyani, S.P.', 'fiya.agista@ayres.local', SHA2('ayres123', 256), 'karyawan', 1),
  ('Tri Widayati', 'tri.widayati@ayres.local', SHA2('ayres123', 256), 'karyawan', 1),
  ('Pascalif Cesarioko Muhammad', 'pascalif.cesarioko@ayres.local', SHA2('ayres123', 256), 'karyawan', 1),
  ('Gabriella Vinda', 'gabriella.vinda@ayres.local', SHA2('ayres123', 256), 'karyawan', 1),
  ('Bayu Apriyanto', 'bayu.apriyanto@ayres.local', SHA2('ayres123', 256), 'karyawan', 1),
  ('Raka Cipluk Prabowo Putro', 'raka.prabowo@ayres.local', SHA2('ayres123', 256), 'karyawan', 1),
  ('Intan Rositasari, S.M.', 'intan.rositasari@ayres.local', SHA2('ayres123', 256), 'karyawan', 1),
  ('Carmenita Wahyu Febriyanti', 'carmenita.wahyu@ayres.local', SHA2('ayres123', 256), 'karyawan', 1),
  ('Mohammad Ilyas Wicaksono', 'mohammad.ilyas@ayres.local', SHA2('ayres123', 256), 'karyawan', 1),
  ('Vina Aulia Rozani', 'vina.rozani@ayres.local', SHA2('ayres123', 256), 'karyawan', 1),
  ('Pipin', 'pipin@ayres.local', SHA2('ayres123', 256), 'karyawan', 1),
  ('Fara', 'fara@ayres.local', SHA2('ayres123', 256), 'karyawan', 1);

INSERT INTO karyawan (
  user_id,
  no_karyawan,
  nama,
  unit,
  jabatan,
  departemen,
  divisi,
  sub_divisi,
  penempatan,
  pembagian_rekapan,
  bank,
  no_rekening,
  status_kepegawaian,
  status_kerja,
  status_data,
  tanggal_kontrak,
  tanggal_selesai_kontrak,
  kenaikan_tiap_tahun
) VALUES
  (
    (SELECT id FROM users WHERE email = 'arya.rahadyan@ayres.local'),
    'TMP-1001',
    'Arya Rahadyan',
    NULL,
    'CEO',
    'Management',
    'Management',
    NULL,
    NULL,
    NULL,
    'BCA',
    NULL,
    'tetap',
    'tetap',
    'aktif',
    NULL,
    NULL,
    0.00
  ),
  (
    (SELECT id FROM users WHERE email = 'vitus@ayres.local'),
    'TMP-1002',
    'Vitus',
    NULL,
    'Director',
    'Management',
    'Management',
    NULL,
    NULL,
    NULL,
    'BCA',
    NULL,
    'tetap',
    'tetap',
    'aktif',
    NULL,
    NULL,
    0.00
  ),
  (
    (SELECT id FROM users WHERE email = 'cb.panjerino@ayres.local'),
    '2003',
    'CB Panjerino Setiaji',
    'Ayres Apparel',
    'Secretary',
    'Direksi',
    'Direksi',
    NULL,
    'Office',
    'Umum Ayres',
    'BCA',
    NULL,
    'tetap',
    'tetap',
    'aktif',
    NULL,
    NULL,
    0.00
  ),
  (
    (SELECT id FROM users WHERE email = 'elnida.rahma@ayres.local'),
    '2058',
    'Elnida Rahma Dian, S.Psi., Psikolog',
    'AVA Sportivo',
    'Supervisor',
    'HRD',
    'HRD',
    NULL,
    'Ayres',
    'Umum AVA',
    'BCA',
    NULL,
    'kontrak',
    'kontrak',
    'aktif',
    '2025-11-17',
    '2026-11-16',
    200000.00
  ),
  (
    (SELECT id FROM users WHERE email = 'humbeina.febriani@ayres.local'),
    '1026',
    'Humbeina Febriani Imlana Putri',
    'AVA Sportivo',
    'Staff',
    'Finance',
    'Finance',
    'Finance',
    'Toko',
    'AVA Sportivo',
    'BCA',
    NULL,
    'tetap',
    'tetap',
    'aktif',
    NULL,
    NULL,
    0.00
  ),
  (
    (SELECT id FROM users WHERE email = 'veni.radstya@ayres.local'),
    '2033',
    'Veni Radstya Sari, S.E.',
    'Ayres Apparel',
    'Staff',
    'Finance',
    'Finance',
    'Finance',
    'Ayres',
    'Ayres Apparel',
    'BCA',
    NULL,
    'tetap',
    'tetap',
    'aktif',
    NULL,
    NULL,
    0.00
  ),
  (
    (SELECT id FROM users WHERE email = 'mizaki.hasan@ayres.local'),
    '1047',
    'Mizaki Hasan',
    'AVA Sportivo',
    'Staff',
    'Finance',
    'Finance',
    'Pajak',
    'Toko',
    'AVA Sportivo',
    'BCA',
    NULL,
    'training',
    'freelance',
    'aktif',
    NULL,
    NULL,
    0.00
  ),
  (
    (SELECT id FROM users WHERE email = 'burhansyah.husna@ayres.local'),
    '2063',
    'Burhansyah Khalifatur Husna',
    'AVA Sportivo',
    'Manager',
    'Marketing',
    'Marketing',
    NULL,
    'Office',
    'AVA Sportivo',
    'BCA',
    NULL,
    'training',
    'freelance',
    'aktif',
    NULL,
    NULL,
    0.00
  ),
  (
    (SELECT id FROM users WHERE email = 'fiya.agista@ayres.local'),
    '2004',
    'Fiya Agista Rahmadiyani, S.P.',
    'Ayres Apparel',
    'Staff',
    'Marketing',
    'Sales & Retail',
    'Customer Service',
    'Ayres',
    'Penjualan Ayres',
    'BCA',
    NULL,
    'tetap',
    'tetap',
    'aktif',
    NULL,
    NULL,
    0.00
  ),
  (
    (SELECT id FROM users WHERE email = 'tri.widayati@ayres.local'),
    '2074',
    'Tri Widayati',
    'Ayres Apparel',
    'Staff',
    'Marketing',
    'Sales & Retail',
    'Customer Service',
    'Ayres',
    'Penjualan Ayres',
    'BCA',
    NULL,
    'training',
    'freelance',
    'aktif',
    NULL,
    NULL,
    0.00
  ),
  (
    (SELECT id FROM users WHERE email = 'pascalif.cesarioko@ayres.local'),
    '1035',
    'Pascalif Cesarioko Muhammad',
    'AVA Sportivo',
    'Staff',
    'Marketing',
    'Sales & Retail',
    'Marketplace',
    'Toko',
    'AVA Sportivo',
    'BCA',
    NULL,
    'kontrak',
    'kontrak',
    'aktif',
    NULL,
    NULL,
    0.00
  ),
  (
    (SELECT id FROM users WHERE email = 'gabriella.vinda@ayres.local'),
    '1034',
    'Gabriella Vinda',
    'AVA Sportivo',
    'Supervisor',
    'Operasional',
    'Logistik',
    NULL,
    'Gudang',
    'AVA Sportivo',
    'BCA',
    NULL,
    'tetap',
    'tetap',
    'aktif',
    NULL,
    NULL,
    0.00
  ),
  (
    (SELECT id FROM users WHERE email = 'bayu.apriyanto@ayres.local'),
    '1038',
    'Bayu Apriyanto',
    'AVA Sportivo',
    'Staff',
    'Operasional',
    'Logistik',
    'Processing',
    'Gudang',
    'AVA Sportivo',
    'BCA',
    NULL,
    'tetap',
    'tetap',
    'aktif',
    NULL,
    NULL,
    0.00
  ),
  (
    (SELECT id FROM users WHERE email = 'raka.prabowo@ayres.local'),
    '1032',
    'Raka Cipluk Prabowo Putro',
    'AVA Sportivo',
    'Staff',
    'Operasional',
    'Logistik',
    'Stok',
    'Gudang',
    'AVA Sportivo',
    'BCA',
    NULL,
    'tetap',
    'tetap',
    'aktif',
    NULL,
    NULL,
    0.00
  ),
  (
    (SELECT id FROM users WHERE email = 'intan.rositasari@ayres.local'),
    '2001',
    'Intan Rositasari, S.M.',
    'Ayres Apparel',
    'Supervisor',
    'Operasional',
    'Produksi',
    NULL,
    'Ayres',
    'Ayres Apparel',
    'BCA',
    NULL,
    'tetap',
    'tetap',
    'aktif',
    NULL,
    NULL,
    0.00
  ),
  (
    (SELECT id FROM users WHERE email = 'carmenita.wahyu@ayres.local'),
    '2029',
    'Carmenita Wahyu Febriyanti',
    'Ayres Apparel',
    'Staff',
    'Operasional',
    'Produksi',
    'Admin Produksi',
    'Ayres',
    'Ayres Apparel',
    'BCA',
    NULL,
    'tetap',
    'tetap',
    'aktif',
    NULL,
    NULL,
    0.00
  ),
  (
    (SELECT id FROM users WHERE email = 'mohammad.ilyas@ayres.local'),
    '2037',
    'Mohammad Ilyas Wicaksono',
    'Ayres Apparel',
    'Staff',
    'Operasional',
    'Produksi',
    'Finishing',
    'Ayres',
    'Ayres Apparel',
    'BCA',
    NULL,
    'tetap',
    'tetap',
    'aktif',
    NULL,
    NULL,
    0.00
  ),
  (
    (SELECT id FROM users WHERE email = 'vina.rozani@ayres.local'),
    '2014',
    'Vina Aulia Rozani',
    'Ayres Apparel',
    'Staff',
    'Operasional',
    'Produksi',
    'Desain',
    'Ayres',
    'Ayres Apparel',
    'BCA',
    NULL,
    'tetap',
    'tetap',
    'aktif',
    NULL,
    NULL,
    0.00
  ),
  (
    (SELECT id FROM users WHERE email = 'pipin@ayres.local'),
    'TMP-1003',
    'Pipin',
    'JNE',
    'Staff',
    'Ekspedisi',
    'Ekspedisi',
    'Ekspedisi',
    'JNE',
    'JNE',
    'BCA',
    NULL,
    'tetap',
    'tetap',
    'aktif',
    NULL,
    NULL,
    0.00
  ),
  (
    (SELECT id FROM users WHERE email = 'fara@ayres.local'),
    'TMP-1004',
    'Fara',
    'JNE',
    'Staff',
    'Ekspedisi',
    'Ekspedisi',
    'Ekspedisi',
    'JNE',
    'JNE',
    'BCA',
    NULL,
    'tetap',
    'tetap',
    'aktif',
    NULL,
    NULL,
    0.00
  );
